# -*- coding: utf-8 -*-
"""banner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WZnT7pBZbyFqP5BwUuJGyKh8UNz7XfrT
"""

from sklearn.metrics import confusion_matrix, accuracy_score
import pandas as pd
import numpy as np
url = 'https://raw.githubusercontent.com/tianzedong/cookie-scan/main/Cookies%20-%20cookie-scripts%20audit.csv'
df = pd.read_csv(url)

y_pred = df["pred"].to_numpy()
y_act = df["act"].to_numpy()
print(confusion_matrix(y_act, y_pred))
print(accuracy_score(y_act, y_pred))